name: Generate PDF

permissions:
  contents: read
  actions: read

on:
  workflow_run:
    workflows: ["Build Astro site"] # Must match build workflow name
    types:
      - completed

jobs:
  html-to-pdf:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: astro-site
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
          path: site

      - name: Convert to PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./site/index.html
          outputFile: ./site/site.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-pdf
          path: ./site/site.pdf
          if-no-files-found: error
